name: wealth_earn
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cached_network_image:
  cool_alert: ^1.1.0
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  introduction_screen: ^2.1.0
  shared_preferences: ^2.0.15

dev_dependencies:

  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/welcome_screen/
